config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  post '/attendence/:event', to: 'attendence#attend'
  resources :events, only: [:index, :new, :create, :show]
  resources :users
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User'
    has_and_belongs_to_many :attendees, class_name: "User"

    scope :upcoming, -> {where("date > ?", Time.now)}
    scope :past, -> {where("date < ?", Time.now)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: 'Event'
  has_and_belongs_to_many :attended_events, class_name: "Event"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendence_controller.rb
class AttendenceController < ApplicationController
    before_action :authenticate_user!

    def attend
        @user = current_user
        @event = params[:event]

        @user.attended_events << @event
        redirect_to root_path
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    
    def index
        @events = Event.all
        @user_signed_in = user_signed_in?
        @current_user = current_user
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @user = current_user
        @event = @user.created_events.build
    end

    def create
        @user = current_user
        @event = @user.created_events.build(event_params)
        if @event.save
            redirect_to events_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
    def event_params
        params.require(:event).permit(:date, :location, :name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        @created_events = current_user.created_events
        @attended_events = current_user.attended_events
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendence_helper.rb
module AttendenceHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>See the events happening soon</h1>
<% @events.upcoming.each do |event| %>
    <p> <strong> <%= event.name %> </strong> | at: <%= event.date %> </p>
    <%= link_to 'More info', event_path(event.id) %>
    <hr>
<% end %>
<h2>Events that happend recently</h2>
<% @events.past.each do |event| %>
    <p> <strong> <%= event.name %> </strong> | at: <%= event.date %> </p>
    <%= link_to 'More info', event_path(event.id) %>
    <hr>
<% end %>
<% unless @user_signed_in %>
    <%= link_to 'Sign in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
<% else %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <%= link_to "Profile", users_path(@current_user.id) %>
<% end %>

app/views/events/new.html.erb
<h1>Create an event</h1>
<%= form_with model: @event, method: "post" do |form| %>
    <%= form.label :name, 'Event name:' %><br>
    <%= form.text_field :name %><br>
    <%= form.label :location, 'Location:' %><br>
    <%= form.text_field :location %><br>
    <%= form.label :date, 'When:' %><br>
    <%= form.datetime_local_field :date %><br>
    <%= form.label :description, 'Description:' %><br>
    <%= form.text_area :description %><br>
    <%= form.submit 'Create Event' %>
<% end %>

app/views/events/show.html.erb
<h3> <%= @event.name %> </h3>
<p> At: <%= @event.date %> </p>
<p> Where: <%= @event.location %> </p>
<p> By: <%= @event.creator %> </p>
<p> About: <%= @event.description %> </p>
<%= link_to "Attend", "/attendence/#{@event.id}", method: "post" %>
<br>
<% @event.attendees.each do |attendee| %>
    <p> <%= attendee.email %> </p>
    <hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"> <%= notice %> </p>
    <p class="alert"> <%= alert %> </p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Events created by you</h1>
<% @created_events.each do |event| %>
    <p> <strong> <%= event.name %> </strong> | at: <%= event.date %> </p>
    <%= link_to 'More info', event_path(event.id) %>
    <hr>
<% end %>
<%= link_to "New event", new_event_path %>
<h3>Upcoming evevnts</h3>
<% @attended_events.upcoming.each do |event| %>
    <p> <strong> <%= event.name %> </strong> | at: <%= event.date %> </p>
    <%= link_to 'More info', event_path(event.id) %>
    <hr>
<% end %>
<h3>Passed events</h3>
<% @attended_events.past.each do |event| %>
    <p> <strong> <%= event.name %> </strong> | at: <%= event.date %> </p>
    <%= link_to 'More info', event_path(event.id) %>
    <hr>
<% end %>